// Tests for .githooks/commit-msg. Run with `pnpm test:hooks`.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { after, test } from "node:test";
import { fileURLToPath } from "node:url";

import { findShell } from "./shell.mjs";

const hook = resolve(dirname(fileURLToPath(import.meta.url)), "../.githooks/commit-msg");
const workDir = mkdtempSync(join(tmpdir(), "commit-msg-"));
after(() => rmSync(workDir, { recursive: true, force: true }));

const shell = findShell();
let counter = 0;

function runHook(message) {
  const file = join(workDir, `msg-${counter++}.txt`);
  writeFileSync(file, message);
  return spawnSync(shell, [hook, file], { encoding: "utf8" });
}

const accepted = [
  ["plain subject", "feat(api): add health checks"],
  ["human co-author", "fix: handle empty slug\n\nCo-Authored-By: Jane Doe <jane@example.com>"],
  ["cursor as a common word", "fix(editor): keep the text created by cursor movement"],
  ["tool name outside an attribution", "docs: explain why Claude Shannon matters"],
  ["ai as a topic", "feat: add AI summary toggle\n\nThe summary itself is not generated yet."],
  ["word that only contains ai", "Signed-off-by: Aiden Maintainer <aiden@example.com>"],
  [
    "attribution inside a verbose diff",
    "chore: tidy hooks\n# ------------------------ >8 ------------------------\n+Co-Authored-By: Claude <noreply@anthropic.com>",
  ],
];

const rejected = [
  ["claude trailer", "feat: x\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>"],
  ["lowercase trailer", "feat: x\n\nco-authored-by: claude <noreply@anthropic.com>"],
  ["generated footer", "feat: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"],
  ["robot emoji alone", "feat: x\n\n🤖 automated change"],
  ["copilot trailer", "feat: x\n\nCo-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>"],
  ["cursor trailer", "feat: x\n\nCo-authored-by: Cursor <cursoragent@cursor.com>"],
  ["chatgpt prose", "feat: x\n\nGenerated by ChatGPT"],
  ["generic ai prose", "feat: x\n\nWritten with the help of an AI assistant"],
  ["generic ai trailer", "feat: x\n\nAssisted-by: AI"],
  ["vendor email", "feat: x\n\nReviewed-by: Bot <noreply@anthropic.com>"],
];

for (const [name, message] of accepted) {
  test(`accepts ${name}`, () => {
    const result = runHook(message);
    assert.equal(result.status, 0, result.stderr);
  });
}

for (const [name, message] of rejected) {
  test(`rejects ${name}`, () => {
    const result = runHook(message);
    assert.equal(result.status, 1, `expected rejection, got: ${result.stdout}${result.stderr}`);
    assert.match(result.stderr, /AI attribution is not allowed/);
  });
}

test("fails when the message file is missing", () => {
  const result = spawnSync(shell, [hook, join(workDir, "missing.txt")], { encoding: "utf8" });
  assert.equal(result.status, 1);
});
